resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:400d8c886191e346d7d18cb089040a18ab481459409a227cfd3ba4c279574e91
  name: quay.io/kevbrain/quinoa-wind-turbine
- digest: sha256:88aa0e2ae4df3594c0e5c6d270efda5a7510f3b424993b8bb3e10c9bee3f864b
  name: quay.io/kevindubois/quinoa-wind-turbine
